//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSoftApp.DBControllerWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.web.gamesoft.pucp/", ConfigurationName="DBControllerWS.DBControllerWS")]
    public interface DBControllerWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.web.gamesoft.pucp/DBControllerWS/queryAllEmployeesIndependentRequ" +
            "est", ReplyAction="http://services.web.gamesoft.pucp/DBControllerWS/queryAllEmployeesIndependentResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoftApp.DBControllerWS.queryAllEmployeesIndependentResponse queryAllEmployeesIndependent(GameSoftApp.DBControllerWS.queryAllEmployeesIndependentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.web.gamesoft.pucp/DBControllerWS/queryAllEmployeesIndependentRequ" +
            "est", ReplyAction="http://services.web.gamesoft.pucp/DBControllerWS/queryAllEmployeesIndependentResp" +
            "onse")]
        System.Threading.Tasks.Task<GameSoftApp.DBControllerWS.queryAllEmployeesIndependentResponse> queryAllEmployeesIndependentAsync(GameSoftApp.DBControllerWS.queryAllEmployeesIndependentRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.web.gamesoft.pucp/DBControllerWS/queryAllDepartmentsIndependentRe" +
            "quest", ReplyAction="http://services.web.gamesoft.pucp/DBControllerWS/queryAllDepartmentsIndependentRe" +
            "sponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentResponse queryAllDepartmentsIndependent(GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.web.gamesoft.pucp/DBControllerWS/queryAllDepartmentsIndependentRe" +
            "quest", ReplyAction="http://services.web.gamesoft.pucp/DBControllerWS/queryAllDepartmentsIndependentRe" +
            "sponse")]
        System.Threading.Tasks.Task<GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentResponse> queryAllDepartmentsIndependentAsync(GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.web.gamesoft.pucp/DBControllerWS/helloRequest", ReplyAction="http://services.web.gamesoft.pucp/DBControllerWS/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoftApp.DBControllerWS.helloResponse hello(GameSoftApp.DBControllerWS.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.web.gamesoft.pucp/DBControllerWS/helloRequest", ReplyAction="http://services.web.gamesoft.pucp/DBControllerWS/helloResponse")]
        System.Threading.Tasks.Task<GameSoftApp.DBControllerWS.helloResponse> helloAsync(GameSoftApp.DBControllerWS.helloRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.web.gamesoft.pucp/")]
    public partial class employee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime birthdayField;
        
        private bool birthdayFieldSpecified;
        
        private string dNIField;
        
        private department departmentField;
        
        private string emailField;
        
        private employee[] employeesField;
        
        private employee headEmployeeField;
        
        private System.DateTime hireDateField;
        
        private bool hireDateFieldSpecified;
        
        private int idField;
        
        private string lastNameField;
        
        private string nameField;
        
        private role roleField;
        
        private double salaryField;
        
        private string secondLastNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("birthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthdaySpecified {
            get {
                return this.birthdayFieldSpecified;
            }
            set {
                this.birthdayFieldSpecified = value;
                this.RaisePropertyChanged("birthdaySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DNI {
            get {
                return this.dNIField;
            }
            set {
                this.dNIField = value;
                this.RaisePropertyChanged("DNI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public department department {
            get {
                return this.departmentField;
            }
            set {
                this.departmentField = value;
                this.RaisePropertyChanged("department");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("employees", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public employee[] employees {
            get {
                return this.employeesField;
            }
            set {
                this.employeesField = value;
                this.RaisePropertyChanged("employees");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public employee headEmployee {
            get {
                return this.headEmployeeField;
            }
            set {
                this.headEmployeeField = value;
                this.RaisePropertyChanged("headEmployee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime hireDate {
            get {
                return this.hireDateField;
            }
            set {
                this.hireDateField = value;
                this.RaisePropertyChanged("hireDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hireDateSpecified {
            get {
                return this.hireDateFieldSpecified;
            }
            set {
                this.hireDateFieldSpecified = value;
                this.RaisePropertyChanged("hireDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string lastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("lastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public role role {
            get {
                return this.roleField;
            }
            set {
                this.roleField = value;
                this.RaisePropertyChanged("role");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public double salary {
            get {
                return this.salaryField;
            }
            set {
                this.salaryField = value;
                this.RaisePropertyChanged("salary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string secondLastName {
            get {
                return this.secondLastNameField;
            }
            set {
                this.secondLastNameField = value;
                this.RaisePropertyChanged("secondLastName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.web.gamesoft.pucp/")]
    public partial class department : object, System.ComponentModel.INotifyPropertyChanged {
        
        private department[] departmentsField;
        
        private employee[] employeesField;
        
        private department headDepartmentField;
        
        private int idField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("departments", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public department[] departments {
            get {
                return this.departmentsField;
            }
            set {
                this.departmentsField = value;
                this.RaisePropertyChanged("departments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("employees", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public employee[] employees {
            get {
                return this.employeesField;
            }
            set {
                this.employeesField = value;
                this.RaisePropertyChanged("employees");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public department headDepartment {
            get {
                return this.headDepartmentField;
            }
            set {
                this.headDepartmentField = value;
                this.RaisePropertyChanged("headDepartment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.web.gamesoft.pucp/")]
    public partial class role : object, System.ComponentModel.INotifyPropertyChanged {
        
        private float maxSalaryField;
        
        private float minSalaryField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public float maxSalary {
            get {
                return this.maxSalaryField;
            }
            set {
                this.maxSalaryField = value;
                this.RaisePropertyChanged("maxSalary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float minSalary {
            get {
                return this.minSalaryField;
            }
            set {
                this.minSalaryField = value;
                this.RaisePropertyChanged("minSalary");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryAllEmployeesIndependent", WrapperNamespace="http://services.web.gamesoft.pucp/", IsWrapped=true)]
    public partial class queryAllEmployeesIndependentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.web.gamesoft.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idDepartment;
        
        public queryAllEmployeesIndependentRequest() {
        }
        
        public queryAllEmployeesIndependentRequest(int idDepartment) {
            this.idDepartment = idDepartment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryAllEmployeesIndependentResponse", WrapperNamespace="http://services.web.gamesoft.pucp/", IsWrapped=true)]
    public partial class queryAllEmployeesIndependentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.web.gamesoft.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoftApp.DBControllerWS.employee[] @return;
        
        public queryAllEmployeesIndependentResponse() {
        }
        
        public queryAllEmployeesIndependentResponse(GameSoftApp.DBControllerWS.employee[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryAllDepartmentsIndependent", WrapperNamespace="http://services.web.gamesoft.pucp/", IsWrapped=true)]
    public partial class queryAllDepartmentsIndependentRequest {
        
        public queryAllDepartmentsIndependentRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="queryAllDepartmentsIndependentResponse", WrapperNamespace="http://services.web.gamesoft.pucp/", IsWrapped=true)]
    public partial class queryAllDepartmentsIndependentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.web.gamesoft.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoftApp.DBControllerWS.department[] @return;
        
        public queryAllDepartmentsIndependentResponse() {
        }
        
        public queryAllDepartmentsIndependentResponse(GameSoftApp.DBControllerWS.department[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://services.web.gamesoft.pucp/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.web.gamesoft.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://services.web.gamesoft.pucp/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.web.gamesoft.pucp/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DBControllerWSChannel : GameSoftApp.DBControllerWS.DBControllerWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DBControllerWSClient : System.ServiceModel.ClientBase<GameSoftApp.DBControllerWS.DBControllerWS>, GameSoftApp.DBControllerWS.DBControllerWS {
        
        public DBControllerWSClient() {
        }
        
        public DBControllerWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DBControllerWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBControllerWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DBControllerWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoftApp.DBControllerWS.queryAllEmployeesIndependentResponse GameSoftApp.DBControllerWS.DBControllerWS.queryAllEmployeesIndependent(GameSoftApp.DBControllerWS.queryAllEmployeesIndependentRequest request) {
            return base.Channel.queryAllEmployeesIndependent(request);
        }
        
        public GameSoftApp.DBControllerWS.employee[] queryAllEmployeesIndependent(int idDepartment) {
            GameSoftApp.DBControllerWS.queryAllEmployeesIndependentRequest inValue = new GameSoftApp.DBControllerWS.queryAllEmployeesIndependentRequest();
            inValue.idDepartment = idDepartment;
            GameSoftApp.DBControllerWS.queryAllEmployeesIndependentResponse retVal = ((GameSoftApp.DBControllerWS.DBControllerWS)(this)).queryAllEmployeesIndependent(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoftApp.DBControllerWS.queryAllEmployeesIndependentResponse> GameSoftApp.DBControllerWS.DBControllerWS.queryAllEmployeesIndependentAsync(GameSoftApp.DBControllerWS.queryAllEmployeesIndependentRequest request) {
            return base.Channel.queryAllEmployeesIndependentAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoftApp.DBControllerWS.queryAllEmployeesIndependentResponse> queryAllEmployeesIndependentAsync(int idDepartment) {
            GameSoftApp.DBControllerWS.queryAllEmployeesIndependentRequest inValue = new GameSoftApp.DBControllerWS.queryAllEmployeesIndependentRequest();
            inValue.idDepartment = idDepartment;
            return ((GameSoftApp.DBControllerWS.DBControllerWS)(this)).queryAllEmployeesIndependentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentResponse GameSoftApp.DBControllerWS.DBControllerWS.queryAllDepartmentsIndependent(GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentRequest request) {
            return base.Channel.queryAllDepartmentsIndependent(request);
        }
        
        public GameSoftApp.DBControllerWS.department[] queryAllDepartmentsIndependent() {
            GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentRequest inValue = new GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentRequest();
            GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentResponse retVal = ((GameSoftApp.DBControllerWS.DBControllerWS)(this)).queryAllDepartmentsIndependent(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentResponse> GameSoftApp.DBControllerWS.DBControllerWS.queryAllDepartmentsIndependentAsync(GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentRequest request) {
            return base.Channel.queryAllDepartmentsIndependentAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentResponse> queryAllDepartmentsIndependentAsync() {
            GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentRequest inValue = new GameSoftApp.DBControllerWS.queryAllDepartmentsIndependentRequest();
            return ((GameSoftApp.DBControllerWS.DBControllerWS)(this)).queryAllDepartmentsIndependentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoftApp.DBControllerWS.helloResponse GameSoftApp.DBControllerWS.DBControllerWS.hello(GameSoftApp.DBControllerWS.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            GameSoftApp.DBControllerWS.helloRequest inValue = new GameSoftApp.DBControllerWS.helloRequest();
            inValue.name = name;
            GameSoftApp.DBControllerWS.helloResponse retVal = ((GameSoftApp.DBControllerWS.DBControllerWS)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoftApp.DBControllerWS.helloResponse> GameSoftApp.DBControllerWS.DBControllerWS.helloAsync(GameSoftApp.DBControllerWS.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoftApp.DBControllerWS.helloResponse> helloAsync(string name) {
            GameSoftApp.DBControllerWS.helloRequest inValue = new GameSoftApp.DBControllerWS.helloRequest();
            inValue.name = name;
            return ((GameSoftApp.DBControllerWS.DBControllerWS)(this)).helloAsync(inValue);
        }
    }
}
